name: Publish Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

# Adding write permissions to the GitHub Token
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier --check "**/*.{ts,js,json,md,yml,yaml}"

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-coverage
          path: coverage/
          retention-days: 5

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: zeybek/camouflage

  publish:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Semantic Release
        id: semantic-release
        if: success() && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Only package and publish if a new release was created
      - name: Package Extension
        if: success() && steps.semantic-release.outputs.new_release_published == 'true'
        run: npm run package

      - name: Publish to Visual Studio Marketplace
        if: success() && steps.semantic-release.outputs.new_release_published == 'true'
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish -p ${VSCE_PAT}

      - name: Create GitHub Release
        if: success() && steps.semantic-release.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.semantic-release.outputs.new_release_version }}
          files: '*.vsix'
          draft: false
          prerelease: false
          generate_release_notes: true
